version: '2.2'

networks:
  laravel:
    name: laravel

volumes:
  mysql8:

services:
  web82:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: web82
    ports:
      - 8080:80
      - 8000:8000
    volumes:
      - ./html:/var/www/html
      - ./config/custom_php.ini:/etc/php/8.2/apache2/conf.d/custom_php.ini
      - ./config/custom_php.ini:/etc/php/8.2/cli/conf.d/custom_php.ini
    networks:
      - laravel
  mysql:
    image: mysql:8.2
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "33066:3306"
    volumes:
      - mysql8:/var/lib/mysql
    networks:
      - laravel  